spring.application.name=foro-service
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/forum_db}
spring.mongodb.database=forum_db
app.seed.enabled=${APP_SEED_ENABLED:true}
app.seed.total-records=${APP_SEED_TOTAL_RECORDS:20000}
app.seed.thread-ratio=${APP_SEED_THREAD_RATIO:0.25}
app.seed.post-ratio=${APP_SEED_POST_RATIO:0.35}
app.seed.message-ratio=${APP_SEED_MESSAGE_RATIO:0.40}